import type { Metadata } from "next";
import { arvo } from "./fonts";
import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={arvo.className}>
                <Navigation />
                {children}
            </body>
        </html>
    );
}
